### ISSUE TITLE
"Work" not displaying in "Manuscript" entry

### ISSUE THREAD

**Issue by wujastyk** [PanditProject/Website#36] opened 2021-09-14 00:33 UTC
These MSS 

- https://www.panditproject.org/entity/110121/manuscript
- https://www.panditproject.org/entity/110120/manuscript
 
contain the [Tattvayogabindu](https://www.panditproject.org/entity/95399/work), but that fact doesn't appear in the MS display.

![image](https://user-images.githubusercontent.com/762246/133174410-902cec14-094e-4f22-81ab-96c0a0c1194f.png)

**Comment by mark-rozen** [comment] 2021-09-14 07:34
It seems like a general problem in the whole database. No manuscript entity currently displays the included work(s) in it.

**Comment by wujastyk** [comment] 2021-09-17 16:59
"Scholarship" entries are also not being displayed.  E.g., in this entry where two scholarshipo entries are recorded but not displayed:

- https://www.panditproject.org/entity/95399/work

**Comment by AmirSimantov** [comment] 2021-11-10 18:40
Closing.

I cannot reproduce. Please re-open if it happens again.

**Closed by AmirSimantov** 2021-11-10 18:40 UTC
